name: "Static Analysis Daily Scan"

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  daily_static_analysis:
    uses: slackhq/snow/.github/workflows/daily_scan.yaml@main
    secrets:       
      SNOW_ALERT_WEBHOOK: ${{ secrets.SNOW_ALERT_WEBHOOK }}
      SNOW_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SNOW_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
