name: "Static Analysis PR Scan"

on: [push, pull_request]

jobs:
  static_analysis:
    uses: slackhq/snow/.github/workflows/github_action.yaml@main
    secrets:       
      SNOW_ALERT_WEBHOOK: ${{ secrets.SNOW_ALERT_WEBHOOK }}
      SNOW_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SNOW_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
